@baseUrl = http://localhost:3000/api

# Categories

# @name getAllCategories
GET {{baseUrl}}/categories

###

# @name addNewCategory
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name": "MacBook"
}

###

# @name updateCategory
PATCH {{baseUrl}}/categories/3
Content-Type: application/json

{
    "name": "IPad"
}

###

# @name removeCategory
DELETE {{baseUrl}}/categories/4
Content-Type: application/json

